version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
    rust: "latest"

python:
  install:
    - path: .
      editable: true
      extra_requirements:
        - test
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
